oracle_main:
  config:
    user: ORA_USER
    password: ORA_PASS
    dsn: ORA_DSN
  decode:
    config:
      password: true
  options:
    lib_dir: DB_LIBDIR
    pool_enabled: true
    pool_size: 4
    arraysize: 5000

db_default:
  config:
    url: DB_URL
  options:
    pool_size: 10
    max_overflow: 20
    pool_pre_ping: true
    pool_recycle: 1800

mail_default:
  config:
    host: SMTP_HOST
    port: SMTP_PORT
    username: SMTP_USER
    password: SMTP_PASS
    from_addr: SMTP_FROM
  decode:
    config:
      password: true
  options:
    timeout: 30
    retry:
      max_attempts: 1
